service: kinesis-examples

provider:
  name: aws
  runtime: nodejs10.x
  environment:

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - "**/*"
    - "!**/node_modules/**"
    - "node_modules/**"

plugins:
  - serverless-offline-kinesis
  - serverless-offline

custom:
  serverless-offline-kinesis:
    endpoint: http://0.0.0.0:4567
    readInterval: 500
    skipCacheInvalidation: false

functions:
  start:
    handler: src/handlers/start/handler.start
    events:
      - http: POST start
    package:
      include:
        - src/handlers/start/handler.js
  process:
    handler: src/handlers/process/handler.process
    events:
      - stream:
          enabled: true
          type: kinesis
          arn: arn:aws:kinesis:eu-west-1:XXXXXX:stream/events
          batchSize: 10
          maximumRetryAttempts: 3
          parallelizationFactor: 2
          startingPosition: TRIM_HORIZON
    package:
      include:
        - src/handlers/process/handler.js